const currencies = [
  { code: "AFN", currency: "Afghani", minorUnit: 2 },
  { code: "EUR", currency: "Euro", minorUnit: 2 },
  { code: "ALL", currency: "Lek", minorUnit: 2 },
  { code: "DZD", currency: "Algerian Dinar", minorUnit: 2 },
  { code: "USD", currency: "US Dollar", minorUnit: 2 },
  { code: "AOA", currency: "Kwanza", minorUnit: 2 },
  { code: "XCD", currency: "East Caribbean Dollar", minorUnit: 2 },
  { code: "ARS", currency: "Argentine Peso", minorUnit: 2 },
  { code: "AMD", currency: "Armenian Dram", minorUnit: 2 },
  { code: "AWG", currency: "Aruban Florin", minorUnit: 2 },
  { code: "AUD", currency: "Australian Dollar", minorUnit: 2 },
  { code: "AZN", currency: "Azerbaijan Manat", minorUnit: 2 },
  { code: "BSD", currency: "Bahamian Dollar", minorUnit: 2 },
  { code: "BHD", currency: "Bahraini Dinar", minorUnit: 3 },
  { code: "BDT", currency: "Taka", minorUnit: 2 },
  { code: "BBD", currency: "Barbados Dollar", minorUnit: 2 },
  { code: "BYN", currency: "Belarusian Ruble", minorUnit: 2 },
  { code: "BZD", currency: "Belize Dollar", minorUnit: 2 },
  { code: "XOF", currency: "CFA Franc BCEAO", minorUnit: 0 },
  { code: "BMD", currency: "Bermudian Dollar", minorUnit: 2 },
  { code: "INR", currency: "Indian Rupee", minorUnit: 2 },
  { code: "BTN", currency: "Ngultrum", minorUnit: 2 },
  { code: "BOB", currency: "Boliviano", minorUnit: 2 },
  { code: "BOV", currency: "Mvdol", minorUnit: 2 },
  { code: "BAM", currency: "Convertible Mark", minorUnit: 2 },
  { code: "BWP", currency: "Pula", minorUnit: 2 },
  { code: "NOK", currency: "Norwegian Krone", minorUnit: 2 },
  { code: "BRL", currency: "Brazilian Real", minorUnit: 2 },
  { code: "BND", currency: "Brunei Dollar", minorUnit: 2 },
  { code: "BGN", currency: "Bulgarian Lev", minorUnit: 2 },
  { code: "BIF", currency: "Burundi Franc", minorUnit: 0 },
  { code: "CVE", currency: "Cabo Verde Escudo", minorUnit: 2 },
  { code: "KHR", currency: "Riel", minorUnit: 2 },
  { code: "XAF", currency: "CFA Franc BEAC", minorUnit: 0 },
  { code: "CAD", currency: "Canadian Dollar", minorUnit: 2 },
  { code: "KYD", currency: "Cayman Islands Dollar", minorUnit: 2 },
  { code: "CLP", currency: "Chilean Peso", minorUnit: 0 },
  { code: "CLF", currency: "Unidad de Fomento", minorUnit: 4 },
  { code: "CNY", currency: "Yuan Renminbi", minorUnit: 2 },
  { code: "COP", currency: "Colombian Peso", minorUnit: 2 },
  { code: "COU", currency: "Unidad de Valor Real", minorUnit: 2 },
  { code: "KMF", currency: "Comorian Franc", minorUnit: 0 },
  { code: "CDF", currency: "Congolese Franc", minorUnit: 2 },
  { code: "NZD", currency: "New Zealand Dollar", minorUnit: 2 },
  { code: "CRC", currency: "Costa Rican Colon", minorUnit: 2 },
  { code: "HRK", currency: "Kuna", minorUnit: 2 },
  { code: "CUP", currency: "Cuban Peso", minorUnit: 2 },
  { code: "CUC", currency: "Peso Convertible", minorUnit: 2 },
  { code: "ANG", currency: "Netherlands Antillean Guilder", minorUnit: 2 },
  { code: "CZK", currency: "Czech Koruna", minorUnit: 2 },
  { code: "DKK", currency: "Danish Krone", minorUnit: 2 },
  { code: "DJF", currency: "Djibouti Franc", minorUnit: 0 },
  { code: "DOP", currency: "Dominican Peso", minorUnit: 2 },
  { code: "EGP", currency: "Egyptian Pound", minorUnit: 2 },
  { code: "SVC", currency: "El Salvador Colon", minorUnit: 2 },
  { code: "ERN", currency: "Nakfa", minorUnit: 2 },
  { code: "SZL", currency: "Lilangeni", minorUnit: 2 },
  { code: "ETB", currency: "Ethiopian Birr", minorUnit: 2 },
  { code: "FKP", currency: "Falkland Islands Pound", minorUnit: 2 },
  { code: "FJD", currency: "Fiji Dollar", minorUnit: 2 },
  { code: "XPF", currency: "CFP Franc", minorUnit: 0 },
  { code: "GMD", currency: "Dalasi", minorUnit: 2 },
  { code: "GEL", currency: "Lari", minorUnit: 2 },
  { code: "GHS", currency: "Ghana Cedi", minorUnit: 2 },
  { code: "GIP", currency: "Gibraltar Pound", minorUnit: 2 },
  { code: "GTQ", currency: "Quetzal", minorUnit: 2 },
  { code: "GBP", currency: "Pound Sterling", minorUnit: 2 },
  { code: "GNF", currency: "Guinean Franc", minorUnit: 0 },
  { code: "GYD", currency: "Guyana Dollar", minorUnit: 2 },
  { code: "HTG", currency: "Gourde", minorUnit: 2 },
  { code: "HNL", currency: "Lempira", minorUnit: 2 },
  { code: "HKD", currency: "Hong Kong Dollar", minorUnit: 2 },
  { code: "HUF", currency: "Forint", minorUnit: 2 },
  { code: "ISK", currency: "Iceland Krona", minorUnit: 0 },
  { code: "IDR", currency: "Rupiah", minorUnit: 2 },
  { code: "IRR", currency: "Iranian Rial", minorUnit: 2 },
  { code: "IQD", currency: "Iraqi Dinar", minorUnit: 3 },
  { code: "ILS", currency: "New Israeli Sheqel", minorUnit: 2 },
  { code: "JMD", currency: "Jamaican Dollar", minorUnit: 2 },
  { code: "JPY", currency: "Yen", minorUnit: 0 },
  { code: "JOD", currency: "Jordanian Dinar", minorUnit: 3 },
  { code: "KZT", currency: "Tenge", minorUnit: 2 },
  { code: "KES", currency: "Kenyan Shilling", minorUnit: 2 },
  { code: "KPW", currency: "North Korean Won", minorUnit: 2 },
  { code: "KRW", currency: "Won", minorUnit: 0 },
  { code: "KWD", currency: "Kuwaiti Dinar", minorUnit: 3 },
  { code: "KGS", currency: "Som", minorUnit: 2 },
  { code: "LAK", currency: "Lao Kip", minorUnit: 2 },
  { code: "LBP", currency: "Lebanese Pound", minorUnit: 2 },
  { code: "LSL", currency: "Loti", minorUnit: 2 },
  { code: "ZAR", currency: "Rand", minorUnit: 2 },
  { code: "LRD", currency: "Liberian Dollar", minorUnit: 2 },
  { code: "LYD", currency: "Libyan Dinar", minorUnit: 3 },
  { code: "CHF", currency: "Swiss Franc", minorUnit: 2 },
  { code: "MOP", currency: "Pataca", minorUnit: 2 },
  { code: "MKD", currency: "Denar", minorUnit: 2 },
  { code: "MGA", currency: "Malagasy Ariary", minorUnit: 2 },
  { code: "MWK", currency: "Malawi Kwacha", minorUnit: 2 },
  { code: "MYR", currency: "Malaysian Ringgit", minorUnit: 2 },
  { code: "MVR", currency: "Rufiyaa", minorUnit: 2 },
  { code: "MRU", currency: "Ouguiya", minorUnit: 2 },
  { code: "MUR", currency: "Mauritius Rupee", minorUnit: 2 },
  { code: "MXN", currency: "Mexican Peso", minorUnit: 2 },
  {
    code: "MXV",
    currency: "Mexican Unidad de Inversion (UDI)",
    minorUnit: 2,
  },
  { code: "MDL", currency: "Moldovan Leu", minorUnit: 2 },
  { code: "MNT", currency: "Tugrik", minorUnit: 2 },
  { code: "MAD", currency: "Moroccan Dirham", minorUnit: 2 },
  { code: "MZN", currency: "Mozambique Metical", minorUnit: 2 },
  { code: "MMK", currency: "Kyat", minorUnit: 2 },
  { code: "NAD", currency: "Namibia Dollar", minorUnit: 2 },
  { code: "NPR", currency: "Nepalese Rupee", minorUnit: 2 },
  { code: "NIO", currency: "Cordoba Oro", minorUnit: 2 },
  { code: "NGN", currency: "Naira", minorUnit: 2 },
  { code: "OMR", currency: "Rial Omani", minorUnit: 3 },
  { code: "PKR", currency: "Pakistan Rupee", minorUnit: 2 },
  { code: "PAB", currency: "Balboa", minorUnit: 2 },
  { code: "PGK", currency: "Kina", minorUnit: 2 },
  { code: "PYG", currency: "Guarani", minorUnit: 0 },
  { code: "PEN", currency: "Sol", minorUnit: 2 },
  { code: "PHP", currency: "Philippine Peso", minorUnit: 2 },
  { code: "PLN", currency: "Zloty", minorUnit: 2 },
  { code: "QAR", currency: "Qatari Rial", minorUnit: 2 },
  { code: "RON", currency: "Romanian Leu", minorUnit: 2 },
  { code: "RUB", currency: "Russian Ruble", minorUnit: 2 },
  { code: "RWF", currency: "Rwanda Franc", minorUnit: 0 },
  { code: "SHP", currency: "Saint Helena Pound", minorUnit: 2 },
  { code: "WST", currency: "Tala", minorUnit: 2 },
  { code: "STN", currency: "Dobra", minorUnit: 2 },
  { code: "SAR", currency: "Saudi Riyal", minorUnit: 2 },
  { code: "RSD", currency: "Serbian Dinar", minorUnit: 2 },
  { code: "SCR", currency: "Seychelles Rupee", minorUnit: 2 },
  { code: "SLL", currency: "Leone", minorUnit: 2 },
  { code: "SGD", currency: "Singapore Dollar", minorUnit: 2 },
  { code: "SBD", currency: "Solomon Islands Dollar", minorUnit: 2 },
  { code: "SOS", currency: "Somali Shilling", minorUnit: 2 },
  { code: "SSP", currency: "South Sudanese Pound", minorUnit: 2 },
  { code: "LKR", currency: "Sri Lanka Rupee", minorUnit: 2 },
  { code: "SDG", currency: "Sudanese Pound", minorUnit: 2 },
  { code: "SRD", currency: "Surinam Dollar", minorUnit: 2 },
  { code: "SEK", currency: "Swedish Krona", minorUnit: 2 },
  { code: "CHE", currency: "WIR Euro", minorUnit: 2 },
  { code: "CHW", currency: "WIR Franc", minorUnit: 2 },
  { code: "SYP", currency: "Syrian Pound", minorUnit: 2 },
  { code: "TWD", currency: "New Taiwan Dollar", minorUnit: 2 },
  { code: "TJS", currency: "Somoni", minorUnit: 2 },
  { code: "TZS", currency: "Tanzanian Shilling", minorUnit: 2 },
  { code: "THB", currency: "Baht", minorUnit: 2 },
  { code: "TOP", currency: "Pa'anga", minorUnit: 2 },
  { code: "TTD", currency: "Trinidad and Tobago Dollar", minorUnit: 2 },
  { code: "TND", currency: "Tunisian Dinar", minorUnit: 3 },
  { code: "TRY", currency: "Turkish Lira", minorUnit: 2 },
  { code: "TMT", currency: "Turkmenistan New Manat", minorUnit: 2 },
  { code: "UGX", currency: "Uganda Shilling", minorUnit: 0 },
  { code: "UAH", currency: "Hryvnia", minorUnit: 2 },
  { code: "AED", currency: "UAE Dirham", minorUnit: 2 },
  { code: "UYU", currency: "Peso Uruguayo", minorUnit: 2 },
  {
    code: "UYI",
    currency: "Uruguay Peso en Unidades Indexadas (UI)",
    minorUnit: 0,
  },
  { code: "UYW", currency: "Unidad Previsional", minorUnit: 4 },
  { code: "UZS", currency: "Uzbekistan Sum", minorUnit: 2 },
  { code: "VUV", currency: "Vatu", minorUnit: 0 },
  { code: "VES", currency: "Bol\u00edvar Soberano", minorUnit: 2 },
  { code: "VND", currency: "Dong", minorUnit: 0 },
  { code: "YER", currency: "Yemeni Rial", minorUnit: 2 },
  { code: "ZMW", currency: "Zambian Kwacha", minorUnit: 2 },
  { code: "ZWL", currency: "Zimbabwe Dollar", minorUnit: 2 },
];

export function getCurrencies() {
  return currencies;
}

export function getMinorUnits(code: string) {
  return currencies.find((x) => x.code === code)?.minorUnit;
}
